import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="home" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row">
        <div className="col-md-12">
          <h1>This is home</h1>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est cumque dolores illo tempora provident iusto eos nam velit, repudiandae, numquam alias molestiae, perspiciatis pariatur fugiat ex sit odit inventore similique?</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est cumque dolores illo tempora provident iusto eos nam velit, repudiandae, numquam alias molestiae, perspiciatis pariatur fugiat ex sit odit inventore similique?</p>
        </div>
      </div>
    </>

      
  )
}
